### ISSUE TITLE
Incorrect index for on-click arrows lesson 5 

### ISSUE THREAD

**Issue by caleb-evans** [dotnet/intro-to-dotnet-web-dev#30]
When I was going through this tutorial I found that since the columns are indexed to one, my board was working incorrectly after inputting this code

```<nav>
	<span title="Click to play a piece" @onclick="() => PlayPiece(0)">🔽</span>
	<span title="Click to play a piece" @onclick="() => PlayPiece(1)">🔽</span>
	<span title="Click to play a piece" @onclick="() => PlayPiece(2)">🔽</span>
	<span title="Click to play a piece" @onclick="() => PlayPiece(3)">🔽</span>
	<span title="Click to play a piece" @onclick="() => PlayPiece(4)">🔽</span>
	<span title="Click to play a piece" @onclick="() => PlayPiece(5)">🔽</span>
	<span title="Click to play a piece" @onclick="() => PlayPiece(6)">🔽</span>
</nav>
```
So I had to start the "PlayPiece" call from index 1-7 instead of 0-6. It was really confusing for me after trying plenty of other things to fix it.

**Comment by cthecreator** [comment]
I was totally wrong, this caused plenty of other unintentional errors. But i found that this code change resolved my issue. 
![image](https://user-images.githubusercontent.com/41302528/234109423-49c3a955-5c31-463c-a5cb-1a2b0b3c46ae.png)

When you change the col to be indexed starting at 1 instead of 0, the game plays correctly

**Comment by RaphaelHaMa** [comment]
I think it has to do with the fact that the CSS file must contain classes for col0 to col6, but the CSS code in the README.md contains the classes col1 to col7.

**Comment by jamesmontemagno** [comment]
I believe that this was fixed.
